### ISSUE TITLE
Callings display error

### ISSUE THREAD

**Issue by prg** [ThingEngineering/wowthing-again#269]
First calling is showing as completed on all my characters, even though I'm certain most of them haven't completed it.

**Comment by prg** [comment]
Alright, so logging into the character seems to help. So the Addon and the subsequent data upload does work, it's just the code that handles calling updates between logins/uploads.

This is the state of my callings on my characters as reported by SavedInstances:
![Screenshot 2022-01-18 215037](https://user-images.githubusercontent.com/101409/150017037-a6581b5b-7541-4cdb-b6f1-24127ac5a29c.png)

This is the state I see on my page:
![Screenshot 2022-01-18 215053](https://user-images.githubusercontent.com/101409/150017144-e4b83c37-7af2-44d8-b52f-57dcb6bef80b.png)

There are still more completed callings on my page than I actually have, because I haven't logged into these characters today. Unfortunately, I don't have much experience with C#, otherwise I'd try and open a pull request.

**Comment by madcowfred** [comment]
The TypeScript code for it is [here](https://github.com/ThingEngineering/wowthing-again/blob/main/frontend/components/home/table/row/HomeTableRowCallings.svelte), it _seems_ like it is roughly correct but I've definitely noticed this issue. I'll try to dig into it again tonight and see if I've just done something stupid.

**Comment by madcowfred** [comment]
I have in fact done something stupid 😓 It only checks if the expiry time is earlier than the reset time, it doesn't check if the expiry time has actually passed. Will push a fix later.

**Comment by madcowfred** [comment]
Should be fixed now

**Comment by prg** [comment]
Unless this isn't rolled out yet, it doesn't seem to work correctly. My characters should be completely empty by now (EU reset last night), but the state is basically still the same as 12 hours ago.

I'll check again tonight after work, maybe I can even take a look at the code myself since it's TypeScript.

**Comment by madcowfred** [comment]
Did you know that if you're making sure that one time (when the daily expires) is larger than another time (the next daily reset), you should use a greater than rather than a lesser than? Weird.

Pushed a quick fix for this, should maybe probably be good now.
